# Generated by Django 4.0.4 on 2022-12-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog_blog_description_blog_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='test_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='doctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_test',
            field=models.CharField(choices=[('Blood test', 'Blood test'), ('Urine test', 'Urine test'), ('Xray', 'Xray'), ('tumor test', 'tumor test'), ('Biochemstry test', 'Biochemstry test')], default='Blood test', max_length=50),
        ),
        migrations.AlterField(
            model_name='lab',
            name='patientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.AlterField(
            model_name='room',
            name='patientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
