# Generated by Django 4.0.4 on 2022-12-30 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lab_test_description_alter_blog_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab/labtest/'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='Lab_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lab'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='daySpent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='room_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.CreateModel(
            name='medicalprogramms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programname', models.CharField(max_length=250)),
                ('programnimage', models.ImageField(blank=True, null=True, upload_to='program/programimg/')),
                ('programdescription', models.TextField()),
                ('amount', models.IntegerField()),
                ('patientId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
